// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeuroSync.Data;

#nullable disable

namespace NeuroSync.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830205835_CorrecaoDadosPais")]
    partial class CorrecaoDadosPais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("NeuroSync.Models.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_agenda");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("agenda");
                });

            modelBuilder.Entity("NeuroSync.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_avaliacao");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("avaliacao");
                });

            modelBuilder.Entity("NeuroSync.Models.Intervencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_intervencao");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("intervencao");
                });

            modelBuilder.Entity("NeuroSync.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_paciente");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("cpf");

                    b.Property<string>("CpfMae")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("cpf_mae");

                    b.Property<string>("CpfPai")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("cpf_pai");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTime?>("DataNascimentoMae")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_nascimento_mae");

                    b.Property<DateTime?>("DataNascimentoPai")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_nascimento_pai");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("EmailMae")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_mae");

                    b.Property<string>("EmailPai")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_pai");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("endereco");

                    b.Property<string>("EscolaEstuda")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("escola_estuda");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_mae");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_pai");

                    b.Property<string>("NomePedagogaPsicologa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_pedagoga_psicologa");

                    b.Property<string>("NomeProfessora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_professora");

                    b.Property<string>("ProfissaoMae")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("profissao_mae");

                    b.Property<string>("ProfissaoPai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("profissao_pai");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("serie");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("telefone");

                    b.Property<string>("TelefoneMae")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("telefone_mae");

                    b.Property<string>("TelefonePai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("telefone_pai");

                    b.HasKey("IdPaciente");

                    b.ToTable("paciente");
                });

            modelBuilder.Entity("NeuroSync.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_pagamento");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_pagamento");

                    b.Property<int?>("IdAvaliacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_avaliacao");

                    b.Property<int?>("IdSessao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sessao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdAvaliacao");

                    b.HasIndex("IdSessao");

                    b.ToTable("pagamento");
                });

            modelBuilder.Entity("NeuroSync.Models.Profissional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("NeuroSync.Models.Prontuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_prontuario");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_criacao");

                    b.Property<int?>("IdAvaliacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_avaliacao");

                    b.Property<int?>("IdIntervencao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_intervencao");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_paciente");

                    b.Property<string>("Queixa")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("queixa");

                    b.HasKey("Id");

                    b.HasIndex("IdAvaliacao");

                    b.HasIndex("IdIntervencao");

                    b.HasIndex("IdPaciente");

                    b.ToTable("prontuario");
                });

            modelBuilder.Entity("NeuroSync.Models.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sessao");

                    b.Property<string>("Anexos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("anexos");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<int>("IdAvaliacao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_avaliacao");

                    b.Property<int?>("IdIntervencao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_intervencao");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("observacoes");

                    b.HasKey("Id");

                    b.HasIndex("IdAvaliacao");

                    b.HasIndex("IdIntervencao");

                    b.ToTable("sessao");
                });

            modelBuilder.Entity("NeuroSync.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_usuario");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("senha");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("NeuroSync.Models.Pagamento", b =>
                {
                    b.HasOne("NeuroSync.Models.Avaliacao", "Avaliacao")
                        .WithMany()
                        .HasForeignKey("IdAvaliacao");

                    b.HasOne("NeuroSync.Models.Sessao", "Sessao")
                        .WithMany()
                        .HasForeignKey("IdSessao");

                    b.Navigation("Avaliacao");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("NeuroSync.Models.Prontuario", b =>
                {
                    b.HasOne("NeuroSync.Models.Avaliacao", "Avaliacao")
                        .WithMany()
                        .HasForeignKey("IdAvaliacao");

                    b.HasOne("NeuroSync.Models.Intervencao", "Intervencao")
                        .WithMany()
                        .HasForeignKey("IdIntervencao");

                    b.HasOne("NeuroSync.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");

                    b.Navigation("Intervencao");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("NeuroSync.Models.Sessao", b =>
                {
                    b.HasOne("NeuroSync.Models.Avaliacao", "Avaliacao")
                        .WithMany("Sessoes")
                        .HasForeignKey("IdAvaliacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeuroSync.Models.Intervencao", "Intervencoes")
                        .WithMany("Sessoes")
                        .HasForeignKey("IdIntervencao");

                    b.Navigation("Avaliacao");

                    b.Navigation("Intervencoes");
                });

            modelBuilder.Entity("NeuroSync.Models.Avaliacao", b =>
                {
                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("NeuroSync.Models.Intervencao", b =>
                {
                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
